#!/bin/bash

# Set the namespace where the ConfigMaps reside
NAMESPACE="your-namespace"

# Get the current date and calculate the date 30 days ago
CURRENT_DATE=$(date +%s)
THIRTY_DAYS_AGO=$((CURRENT_DATE - (30 * 24 * 60 * 60)))

# Retrieve the list of ConfigMaps in the specified namespace
CONFIGMAPS=$(kubectl get configmaps -n $NAMESPACE -o jsonpath='{.items[*].metadata.name}')

# Iterate through each ConfigMap and check if it's older than 30 days
for CONFIGMAP in $CONFIGMAPS; do
    CREATION_TIMESTAMP=$(kubectl get configmap $CONFIGMAP -n $NAMESPACE -o jsonpath='{.metadata.creationTimestamp}')
    CREATION_DATE=$(date -d $CREATION_TIMESTAMP +%s)

    if [[ $CREATION_DATE -lt $THIRTY_DAYS_AGO ]]; then
        echo "Deleting ConfigMap: $CONFIGMAP"
        kubectl delete configmap $CONFIGMAP -n $NAMESPACE
    fi
done


Older than 30 days


kubectl get configmap -n <namespace> -o json | jq '.items[] | select((now - (.metadata.creationTimestamp | fromdate)) > 2592000)'




kubectl get configmaps -n <namespace> --no-headers=true > configmaps.txt

touch filtered_configmaps.txt

while read -r line; do
  configmap_name=$(echo "$line" | awk '{print $1}')
  creation_timestamp=$(echo "$line" | awk '{print $5}')
  creation_date=$(date -d "$creation_timestamp" +%s)
  current_date=$(date +%s)
  difference=$(( (current_date - creation_date) / (60*60*24) ))

  if [ $difference -gt 30 ]; then
    echo "$line" >> filtered_configmaps.txt
  fi
done < configmaps.txt


cat filtered_configmaps.txt
