#!/bin/bash

total=`free -mw | awk '/^Mem/  {print $2}'`
buffers=`free -mw | awk '/^Mem/  {print $6}'`
cache=`free -mw | awk '/^Mem/  {print $7}'`
free=`free -mw | awk '/^Mem/  {print $4}'`

memutilization=`echo "scale = 2; ( $total - $free - $buffers - $cache ) /  $total * 100 " | bc -l`
echo "Memory Utilized = ( ( Total - Free ) / Total * 100 ) =" $memutilization "%"
